name: Build and check image

on: push

jobs:
  verify-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space and remove dotnet
        run: |
          echo "Free space:"
          df -h
          sudo rm -rf /usr/share/dotnet
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: ooil version
        uses: docker://itisfoundation/ci-service-integration-library:v1.0.1-dev-32
        with:
          args: ooil --version
      - name: Assemble docker-compose spec
        uses: docker://itisfoundation/ci-service-integration-library:v1.0.1-dev-32
        with:
          args: ooil compose
      - name: Check disk space
        run: |
          echo "Free space:"
          df -h
      - name: Build all images if multiple
        uses: docker://itisfoundation/ci-service-integration-library:v1.0.1-dev-32
        with:
          args: docker-compose build
